<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:import href="uri_of_ext.xsl" />

  <xsl:template match="extension|draft|proposal">
    <xsl:comment>AUTOGENERATED FILE - DO NOT EDIT - SEE MAKEFILE FOR DETAILS</xsl:comment>    
    <xsl:call-template name="copy-template" />
  </xsl:template>

  <xsl:template match="*|node()" name="copy-template">
    <xsl:copy>
      <xsl:copy-of select="@*" />
      <xsl:apply-templates select="node()" />
    </xsl:copy>
  </xsl:template>

  <xsl:template match="history">
    <xsl:copy>
      <xsl:apply-templates select="node()" />
      <xsl:copy-of select="document('auto_history.xml')/history/*" />
    </xsl:copy>
  </xsl:template>

  <xsl:template match="template[@name='uri_to_khronos']">
    <xsl:apply-templates select="document(@src)" mode="uri_to_khronos"/>
  </xsl:template>

  <xsl:template match="extension|draft" mode="uri_to_khronos">
    <tr>
      <td>
        <a>
          <xsl:attribute name="href">
            <xsl:call-template name="uri_of_ext" />
          </xsl:attribute>
          <xsl:call-template name="uri_of_ext" />
        </a>
      </td>
      <td><ext name="{name}" /></td>
    </tr>
  </xsl:template>

  <xsl:template match="registry" mode="uri_to_khronos">
    <table id="uri_to_khronos">
      <tr><th>URI</th><th>Khronos WebGL Extension</th></tr>
      <xsl:apply-templates select="extension|draft" mode="uri_to_khronos">
        <xsl:sort select="number" data-type="number" order="ascending" />
      </xsl:apply-templates>
    </table>
  </xsl:template>
</xsl:stylesheet>

