<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="text" />

  <xsl:template match="include">
    <xsl:value-of select="document(@src)/json/text()" />
  </xsl:template>

  <xsl:template match="script">
//AUTOGENERATED FILE - DO NOT EDIT - SEE Makefile
    <xsl:apply-templates />
  </xsl:template>
</xsl:stylesheet>

